### ISSUE TITLE
Individual Player Page

### ISSUE THREAD

**Issue by mdaye13** [firstlinestats/statsenforcer#10]
Need everything here. Possibly link to NHL.com page, include season stats and last ~30 games stats and charts

**Comment by mdaye13** [comment]
Added data and form

**Comment by svancise** [comment]
I'll tackle the graphs.

**Comment by svancise** [comment]
Bubble graph is in place/placeholder right now. May need to look at the type of data we are displaying there, right now it only returns one season so we will need to probably allow for multiple seasons.
