### ISSUE TITLE
Move CSS styling of graphs to just D3 styling

### ISSUE THREAD

**Issue by mdaye13** [firstlinestats/statsenforcer#39]
CSS stylings of graphs don't get picked up by canvg, making the PNG version of graphs different from in site ones.

Check on

- [ ] Team Page
- [ ] Teams Page
- [ ] Player Page
- [ ] Players Page
- [ ] Game Page
- [ ] Goalies Page
- [ ] Goalie Page

**Comment by svancise** [comment]
I'll take care of this, did it for the old "bubble" graphs.

**Comment by mdaye13** [comment]
holding off on adding charts to goalies pages and goalie page for now so we don't have to duplicate work or doing this again for those pages

**Comment by svancise** [comment]
Believe this is done
